<?

	/**
	 * ErrorController
	 * Handles error pages generated by the application
	 *
	 * @package PharosPHP.Application.Controllers
	 * @author Matt Brewer
	 **/
	
	class ErrorController extends ApplicationController {
		
		
		/**
		 * __construct
		 * Constructor
		 *
		 * @return void
		 * @author Matt Brewer
		 **/
		
		public function __construct() {
			parent::__construct();
			$this->output->layout = "session-controller-login";
		}
		
	
		/**
		 * __missingControllerAction
		 * Called by the application if the method was not defined.  
		 * The method should be numeric for HTTP Error codes, so that was not a valid method name in PHP. 
		 * Hence the dynamic nature of this solution.
		 *
		 * @param string $class
		 * @param string $method
		 * @param array $params
		 *
		 * @throws ControllerActionNotFoundException
		 * 
		 * @return void
		 * @author Matt Brewer
		 **/

		public function __missingControllerAction($class, $method, array $params=array()) {
			if ( !in_array($method, array(400, 401, 403, 404)) ) {
				throw new ControllerActionNotFoundException($class, $method);
			}
			$this->output->view("errors/$method.php");
			$this->output->cache(1 * Cache::WEEKS);
		}
		
	} 

?>