database:
    host: localhost
    username: macfanat_matt
    password: '6513#*trin'
    name: macfanat_cms
    
filesystem:
    uploads_directory: uploads
    xml_direcotry: xml
    
modules:
    autoload:
        - console
        - images
        - cron
        
routes:
    root: 
        controller: UsersController
    connections:

        - 
            pattern: "posts/nyt/favorites/:id/?"
            controller: UsersController
            action: some_method
            params: 
                - { key: ":repost", pattern: (true|false) }

        -
            pattern: "post-:id/:repost/:month/?"
            controller: PostsController
            action: edit
            params:
                ":repost":  "(true|false)"
                ":month": "([[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2})"

        # Default matching pattern is:
        # - { pattern: ":controller/:action/.*" }


system:
    version: 1.5
    default_app_id: 1
    cache: true
    site:
        name: "CMSLite"
    
    
users:
    levels:
        basic: 1
        admin: 4
        super: 5
    
    