database:
    host: localhost
    username: macfanat_matt
    password: '6513#*trin'
    name: macfanat_cms
    
filesystem:
    uploads_directory: uploads
    xml_direcotry: xml
    
modules:
    system:
        - console
        - images
        - cron
    user:
        
routes:
    root: 
        controller: UsersController
    
system:
    version: 1.5
    default_app_id: 1
    site:
        name: "CMSLite"
    
    
users:
    levels:
        basic: 1
        admin: 4
        super: 5
    
    